#!/bin/zsh -e

MYDIR=${0:a:h}
cd $MYDIR/..

nok=0
nfail=0

must_fail_eslint() {
  local desc=$1; shift
  if echo "$@" | npx eslint --stdin --stdin-filename test.js 2>&1 >| log; then
    echo "FAIL: $desc -- expected lint failure but got success"
    nfail=$((nfail+1))
    cat log
  else
    if grep -q "$desc" log; then
      echo "OK: $desc caught correctly"
      nok=$((nok+1))
    else
      nfail=$((nfail+1))
      cat log
    fi
  fi
  rm -f log
}

must_fail() {
  local desc=$1; shift
  if "$@" 2>/dev/null; then
    echo "FAIL: $desc -- expected lint failure but got success"
    nfail=$((nfail+1))
  else
    echo "OK: $desc caught correctly"
    nok=$((nok+1))
  fi
}

must_fail_eslint  prefer-const  'let x = 3; alert(x)'
must_fail_eslint  @stylistic/quotes  'const x = "3"; alert(x)'
must_fail_eslint  @stylistic/quotes  'const x = `no dollar-curly in template`'
must_fail_eslint  no-shadow  $'const x = 3; alert(x)\n{ const x = 4; alert(x) }'
must_fail_eslint  prefer-template  "const n = 'world'; alert('hello ' + n)"
must_fail_eslint  no-unused-vars  'const x = 3'
must_fail_eslint  eqeqeq  'alert(3 == 4)'
must_fail_eslint  arrow-body-style  'alert([1,2].map(x => { return x * 2 }))'
must_fail_eslint  arrow-parens  'setTimeout(x => alert(x), 100)'
must_fail_eslint  prefer-arrow-callback  'setTimeout(function() { alert(33) }, 10)'
must_fail_eslint  comma-dangle  $'const x = {\na: 3\n}'


for TEST in test/should-fail/*.js; do
  echo TEST=$TEST

  if grep -q 'lint-test: deno-check-only' $TEST; then
    echo "(skipping eslint -- deno-check-only)"

    if ( deno check --allow-import --vendor --config test/should-fail/deno.json $TEST ) 2>&1 \
        | grep -EA4 "Did you forget to use 'await'|does not exist on type 'Promise"; then
      echo "OK: TEST=$TEST deno-check caught correctly"; nok=$((nok+1))
    else
      echo "FAIL: TEST=$TEST deno-check -- expected error, found none"; nfail=$((nfail+1))
    fi
  else
    if [ $TEST = test/should-fail/fetch2.js ]; then
      # clean without LINT_PROMISES, caught with it
      npx eslint --no-ignore $TEST  &&  nok=$((nok+1))
    else
      must_fail "TEST=$TEST"                                     npx eslint --no-ignore $TEST
    fi
    must_fail   "TEST=$TEST LINT_PROMISES=1" env LINT_PROMISES=1 npx eslint --no-ignore $TEST
  fi

  echo "$nok passed, $nfail failed"
  echo '========================================================'
done

(( nfail == 0 ))
