# Minimal CI/CD - copy this into your repo in .github/workflows/ subdir.
# https://github.com/internetarchive/dyno/blob/main/.github/workflows/cicd.yml  shows [test] jobs
name: CICD
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       contents: read
       packages: write
       id-token: write
    steps:
      # https://github.com/internetarchive/build/blob/main/action.yml
      - uses: internetarchive/build@v1
        with:
          regpw: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/internetarchive/nomad/master
    steps:
    - env:
        BASE_DOMAIN: dev.archive.org
        NOMAD_ADDR: https://nom.us.archive.org:4646
        NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # https://gitlab.com/internetarchive/nomad/-/blob/master/deploy.sh
      run: /deploy.sh
