#!/bin/zsh -e

# For a repo that's using our container in their CI [test] phase, [lint] job,
# we'll use any of these files from _their_ repo (that they've customized).
# (Otherwise, use these files from us, the 'dyno' repo, located in /app/)

MYDIR=${0:a:h}

typeset -a REMOVES
REMOVES=()
for i in package.json eslint.config.js deno.json tsconfig.json node_modules; do
  if [ ! -e $i ]; then
    ln -s $MYDIR/$i
    REMOVES+=($i)
  fi
done
trap "{ rm -f $REMOVES; }" EXIT

if [ $# -eq 0 ]; then 1=.; fi

( set -x; deno lint -c deno.json "$@" )

( set -x; LINT_PROMISES=1 npx eslint "$@" )

if [ -e vendor ]; then
  if [ -n "$(find vendor -mindepth 1 -type f -mtime +21 -print -quit 2>/dev/null)" ]; then
    ecno
    echo "vendor/ HAS FILES > 3 WEEKS OLD -- CONSIDER REBUILDING ENTIRELY:"
    echo "  find vendor -mindepth 1 -delete  &&  deno check --allow-import --vendor ."
    echo
  fi

  # Promises - look for missing `await` in callers of `async` functions
  # Promises - look for missing parens, eg: `await exe('ls').trim()` => `(await exe('ls')).trim()`
  echo deno check --allow-import --vendor "$@"
  if ( deno check --allow-import --vendor "$@" ) 2>&1 \
      |grep -EA4 "Did you forget to use 'await'|does not exist on type 'Promise<any>'"; then
    echo "promises made, promises broken"; exit 1
  fi
fi

echo LINT SUCCESS
