#!/bin/zsh -e

# For a repo that's using our container in their CI [test] phase, [lint] job,
# we'll use any of these files from _their_ repo (that they've customized).
# (Otherwise, use these files from us, the 'eslint' repo, located in /app/)

MYDIR=${0:a:h}

typeset -a REMOVES
REMOVES=(.proms)
for i in package.json .eslintrc.cjs .eslint.await.finder.cjs .eslint.await.finder.tsconfig.json deno.json tsconfig.json node_modules; do
  if [ ! -e $i ]; then
    ln -s $MYDIR/$i
    REMOVES+=($i)
  fi
done
trap "{ rm -f $REMOVES; }" EXIT

ARGS=.
if [ $# -gt 0 ]; then ARGS="$@"; fi

set -x

deno lint -c deno.json "$ARGS"
npx eslint "$ARGS"

# Promises - look for missing `await` in callers of `async` functions
# Promises - look for missing parens, eg: `await exe('ls').trim()` => `(await exe('ls')).trim()`
#            ^^ cheap approximate:  git grep -P 'await[^)]+\)\.'
npx eslint -c .eslint.await.finder.cjs "$ARGS" \
  |egrep "\.js|floating-promises" \
  |egrep -B1 floating-promises \
  |tee .proms

npx tslint --type-check -p tsconfig.json "$ARGS" 2>&1 \
  |fgrep -v www/jw/8/jwplayer.js \
  |fgrep Promise \
  |fgrep roperty \
  |fgrep "does not exist" \
  |tee -a .proms

if [ -s .proms ]; then
  echo "promises made, promises broken"
  exit 1
fi

set +x
echo LINT SUCCESS
