# This does a (multi-architecture) [build]
# @see README.md for full CI/CD pipeline examples.

on: push
jobs:
  cicd:
    # https://github.com/internetarchive/cicd
    uses: internetarchive/cicd/.github/workflows/cicd-multi-arch.yml@main
